### ISSUE TITLE
Woody Jean-Louis

### ISSUE THREAD

**Issue by Woodyjl** [umiami-web-design/css-project#17]
Hey Professor, before you look at the site you will notice that the site is a mess. For some reason I'm getting a 404 when trying to retrieve css/style.css. I've tried to figure out what was going on, but I wasn't able to get a solution. Can you please download the files instead in order to grade?

https://woodyjl.github.io/resume

**Comment by ebrown15** [comment]
Grade is posted in CaneLink.
